FROM node:22-alpine AS deps
ARG AUTH_SECRET
ARG DATABASE_URL
ARG DIRECT_URL
ARG JWT_SECRET
ARG MONGODB_URI
ARG MYSQL_URL
ARG NEXTAUTH_SECRET
ARG NEXTAUTH_URL
ARG POSTGRES_URL
ARG REDIS_URL
ARG SECRET_KEY
ARG SESSION_SECRET
ARG AUTH_SECRET
ARG DATABASE_URL
ARG DIRECT_URL
ARG JWT_SECRET
ARG MONGODB_URI
ARG MYSQL_URL
ARG NEXTAUTH_SECRET
ARG NEXTAUTH_URL
ARG POSTGRES_URL
ARG REDIS_URL
ARG SECRET_KEY
ARG SESSION_SECRET
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm ci

FROM node:22-alpine AS builder
ARG AUTH_SECRET
ARG DATABASE_URL
ARG DIRECT_URL
ARG JWT_SECRET
ARG MONGODB_URI
ARG MYSQL_URL
ARG NEXTAUTH_SECRET
ARG NEXTAUTH_URL
ARG POSTGRES_URL
ARG REDIS_URL
ARG SECRET_KEY
ARG SESSION_SECRET
ARG AUTH_SECRET
ARG DATABASE_URL
ARG DIRECT_URL
ARG JWT_SECRET
ARG MONGODB_URI
ARG MYSQL_URL
ARG NEXTAUTH_SECRET
ARG NEXTAUTH_URL
ARG POSTGRES_URL
ARG REDIS_URL
ARG SECRET_KEY
ARG SESSION_SECRET
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .
RUN npx prisma generate
RUN npm run build

FROM node:22-alpine AS runner
ARG AUTH_SECRET
ARG DATABASE_URL
ARG DIRECT_URL
ARG JWT_SECRET
ARG MONGODB_URI
ARG MYSQL_URL
ARG NEXTAUTH_SECRET
ARG NEXTAUTH_URL
ARG POSTGRES_URL
ARG REDIS_URL
ARG SECRET_KEY
ARG SESSION_SECRET
ARG AUTH_SECRET
ARG DATABASE_URL
ARG DIRECT_URL
ARG JWT_SECRET
ARG MONGODB_URI
ARG MYSQL_URL
ARG NEXTAUTH_SECRET
ARG NEXTAUTH_URL
ARG POSTGRES_URL
ARG REDIS_URL
ARG SECRET_KEY
ARG SESSION_SECRET
WORKDIR /app
ENV NODE_ENV=production
ENV PORT=3000

COPY --from=builder /app/public ./public
COPY --from=builder /app/.next/standalone ./
COPY --from=builder /app/.next/static ./.next/static

EXPOSE 3000
CMD ["node", "server.js"]
